version: "3.3"  # optional since v1.27.0
services:
  web:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./bancoSQL:/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456